wandb_version: 1

batch_size:
  desc: null
  value: 16
epochs:
  desc: null
  value: 10
learning_rate:
  desc: null
  value: 0.001
optimiser:
  desc: null
  value: Adagrad
_wandb:
  desc: null
  value:
    python_version: 3.11.5
    cli_version: 0.15.12
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1699910462.936437
    t:
      1:
      - 1
      - 41
      - 55
      2:
      - 1
      - 41
      - 55
      3:
      - 1
      - 2
      - 23
      - 37
      4: 3.11.5
      5: 0.15.12
      8:
      - 5
      13: linux-x86_64
